# Generated by Django 4.0.4 on 2022-04-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_order_date_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
